### ISSUE TITLE
Video demonstration is not available

### ISSUE THREAD

**Issue by Sriharsha244** [developerforce/pub-sub-api#10]
A video demonstrating this app in action can be found on the [TrailheaDX](https://www.salesforce.com/trailheadx) website. After registering/logging in, go to [Product & Partner Demos](https://www.salesforce.com/trailheadx) and click Integrations & Analytics > Platform APIs to watch it.

**Video demonstration is not available, could you please point to right one**

**Comment by pozil** [comment]
@Sriharsha244 you can now refer to this video: https://www.youtube.com/watch?v=g9P87_loVVA
