### ISSUE TITLE
Can anyone share a Java client connecting to Salesforce pub-sub-api pls?

### ISSUE THREAD

**Issue by malakasilva** [developerforce/pub-sub-api#17]

**Comment by malakasilva** [comment]
Hello,

I created the stub using MVN io.grpc.

But stuck to publish messages. Please help.
Eg: 
    public static void main( String[] args )
    {

        PubSubBlockingStub publishStub = PubSubBlockingStub.new
    }

**Comment by hechuan9** [comment]
Same here. No idea how to create a java client

**Comment by pozil** [comment]
Hi all, here’s a Java client: https://github.com/pozil/pub-sub-api-java-client
It’s subscribe only and rough code at this point, I’ll have to implement an example of publish but it’s a start.

**Comment by pozil** [comment]
See #19
