### ISSUE TITLE
Missing production endpoint

### ISSUE THREAD

**Issue by lekkimworld** [developerforce/pub-sub-api#18]
The endpoint is currently set to api.pilot.pubsub.salesforce.com:7443 - at least in the Go example. What's the GA production endpoint? I see api.pubsub.salesforce.com:7443 works with my own code but it would be good to have the right endpoint in the repo.

**Comment by lekkimworld** [comment]
Found a reference to the API endpoint on https://developer.salesforce.com/docs/platform/pub-sub-api/guide/qs-build-python-client.html but think it seems to be more front and center. Pretty hard to find.

**Comment by knhage** [comment]
The endpoint is now doc'd here: https://developer.salesforce.com/docs/platform/pub-sub-api/guide/grpc-api.html#pub/sub-api-endpoint

**Comment by herinckc** [comment]
I've updated the Go example to point to the GA endpoint as part of https://github.com/developerforce/pub-sub-api/pull/23. Closing this issue out now
